### ISSUE TITLE
Private Datasets Can't be Package_search()ed with API

### ISSUE THREAD

**Issue by rubixcuban** [GSA/project-open-data-dashboard#78]
If a package is private and you present the Authorization or the X-CKAN-API-Key in the request header (I've tried both), package_search doesn't work.  I've tried it with public to make sure my syntax is good.  It's my dataset, package_search with the appropriate header should work.

**Comment by philipashlock** [comment]
Which website are you working with? This repo isn't for a CKAN catalog, it's for labs.data.gov/dashboard. If your issue is with inventory.data.gov you can file an issue at https://github.com/GSA/enterprise-data-inventory/issues

Also, I believe this is a core CKAN constraint, not something that's specific to a data.gov implementation.
