### ISSUE TITLE
Add under EDI tab: Publicly Available Version of EDI

### ISSUE THREAD

**Issue by jlberryhill** [GSA/project-open-data-dashboard#79]
Under the EDI tab, can we please add a spot for the recent IDC question "May OMB publicly release the agency’s EDI?" As @philipashlock suggested to me earlier, we should make clear that this is for informational purposes only, and that agencies are not being evaluated on whether they say yes or no.

For the 2/28 submission at least, could you please also add a spot to link to the EDIs that we release via FOIA?

**Comment by philipashlock** [comment]
@jlberryhill Maybe there's an alternate way to handle this so that we could also indicate if the agency had incorporated their non-public EDI information into their PDL (merged their EDI with their PDL) or made a redacted EDI available as one of their datasets. 

As for the link to the EDI, if it's not available from the PDL, I think OMB could just add the link in the main notes field for the EDI or the overall notes field for the milestone.

**Comment by rebeccawilliams** [comment]
Moot.
